MedShake/MedShakeEHR-base

installer/self-installer.php

$ret est un array et non une string, la fonction strpos retournait une erreur.
Ce correctif filtre $ret à la recherche d'une erreur.

Correction d'un bug avec le return de composer lors de l'installation automatique

---

controlers/patient/actions/inc-ajax-prepareReceptionDoc.php

Fix une erreur de syntaxe qui fait planter php-fpm au niveau du contrôleur ajax pour préparer la réception de document phone capture.

fix: ajax phonecapture

---

cron/rappelsMails.php

Résous un soucis avec la valeur du `$homepaht` dans la tache cron lié a l'envoie de rappel par mail (désormais relative au script et non au répertoire courant de l’exécution du script).
Résous aussi un problème de saut de ligne mal formé dans les mail et empêche d’expédier par accident deux fois la même campagne.

Fix de la tache cron pour l'evoie de rappel mail

---

.editorconfig

Simple ajout d'un fichier pour [EditorConfig](https://editorconfig.org/) afin d'aider à normer le style de codage entre plusieurs éditeurs.

add: .editorconfig file

---

public_html/js/general.js
templates/base/pageTopNavbar.html.twig

Pour les grosse journée ou sur les petits écran, la liste *patients of the day* dépasse de l'écran ce qui empêche de voire les dernières entrées.
Ajoute une attribut `overflow-y` au `<div>` conteneur de la liste et change automatiquement sa auteur quant le fenêtre est redimensionné.

fix(): overflow sur la liste des patients du jour

---

public_html/install.php

Modification de l'installateur pour qu'il puisse aussi être utilisé via la ligne de commande.
Parfois nous pouvons avoirs besoin de lancer l'installation MedShakeEHR via la ligne de commande (cas de la mise en place d'une image Docker ou toute autre cas d'installation automatiser via script ou Ansible). Ce PR apporte des modifications à l'installateur pour qu'il puisse aussi être utilisé via la ligne de commande avec des arguments.
Le comportement par défaut de l'installateur (via l’exécution web)  n'est pas modifié mis a part l'ajout d'une option afin de désactiver la saisie des identifiants administrateur pour la base de donnée (ce qui permet de crée soit même la base de donnée et son utilisateur pour MedShakeEHR en amont et nous évite la création d'un utilisateur administrateur pour la …

Cli installer

---

public_html/js/rechercher.js

Simple ajout de la date de naissance du patient à la recherche au moment de la lecture de la carte vital via VitalOnline.
Permet de mieux différentier les homonymes.

feat: ajout date de naissance pour recherche vital

---

class/msCourrier.php
class/msPDF.php
templates/models4printAuto/base-page-closeHtml.html.twig
templates/models4printAuto/base-page-headAndFoot.html.twig
templates/models4printAuto/base-page-headAndNoFoot.html.twig
templates/models4printAuto/base-page-noHeadAndNoFoot.html.twig
templates/models4printAuto/certif-certificatVierge.html.twig
templates/models4printAuto/courrier-courrierVierge.html.twig
templates/models4printAuto/courrier-ttEnCours.html.twig
templates/models4printAuto/csBase.html.twig
templates/models4printAuto/csImportee.html.twig
templates/models4printAuto/facture.html.twig
templates/models4printAuto/ordonnanceALD.html.twig
templates/models4printAuto/ordonnanceAnonyme.html.twig
templates/models4printAuto/ordonnanceAnonymeALD.html.twig
templates/models4printAuto/ordonnanceBody.html.twig
templates/models4printAuto/rapportImagesDicom.html.twig
templates/models4printAuto/styles.html.twig

Permet de récupérer dans le tag `page.courrier` les donnée de l'utilisateur actif et de l'auteur initial (récupérer via les donnée le l'objet lui même) dans les documents de type courrier. Pour les nouveau courrier l'auteur initial est l'utilisateur actif et pour les modifications de courrier existant l'auteur initial est récupérer via le fromID de la donnée elle même.
Ajoute aussi une copie des templates de base dans `templates/models4PrintAuto` afin de pouvoir choisir des templates ou les donnée des entêtes et du footer son récupéré directement depuis les données pro du praticien (sans pour autant modifier les templates de bases).
C'est très utilise dans le cas d'un cabinet avec de nombreux praticiens et/ou quant ils sont amenés à changer ou être remplacés régulièrement.

fix: msPDF permet de récupérer AuteurInitial et UtilisateurActif dans les template de courrier

---

class/msObjet.php

Dans la requette sql de la fonction pour le `where o.typeID in` les
valeur passé entre `()` pour le `in` sont entres `'` ce qui empèche la
requette re trourner un résultat pour tout les typeID fournis.

fix(msObjet::getObjetChildsByNames) : valeurs entre  quote dans sqlQuery

---

class/msCourrier.php
class/msData.php

Empêche php 7 de chouiner que certaine fonction de `msData` sont appelé sans instancier la classe.

fix(msData): propriété statique sur certaine fonction

---

controlers/patient/actions/inc-ajax-extractMailForm.php
templates/base/patient/mailForm.html.twig

Juste un oublie de l'inclusion du code js des formulaire dans les formulaires d'envoi de courriel.

fix(form courriel): inclus de js des fromulaire dans ceux des courriel

---

class/msSQL.php

Bloquant lors de la création d'un premier utilisateur sous MySQL 8.

Fix: MySQL 8 mots clés réservés ON DUPLICATE KEY

---

installer/debian-bash-installer.sh

Fixe un bug sur Windows subsytem for Linux qui ne lance pas mariadb à la suite de son installation

fix: mariadb not started on WSL

---

.gitignore
Vagrantfile
tools/vagrant/README.md
tools/vagrant/main.yml
tools/vagrant/secrets-sample.yml
tools/vagrant/templates/20auto-upgrades.j2
tools/vagrant/templates/50unattended-upgrades.j2
tools/vagrant/templates/msehr.vhost.conf.j2
tools/vagrant/templates/msehrCli.sh.j2
tools/vagrant/templates/php.ini.j2

Ajout d'un Vagrantfile pour générer une VM Virtualbox automatiquement approvisionnée par Ansible 
- installation auto en https jusqu'à l'étape first login
- permettra de travailler et tester les différentes branches et les tags ultérieurs à l'implémentation dans un environnement commun
- permet de choisir un environnement php prod ou dev
- pare-feux et mise à jour auto
- possibilité de custom la puissance de la VM
- ajout d'un fichier .gitignore

add: Vagrantfile

---

tools/vagrant/main.yml
tools/vagrant/secrets-sample.yml
tools/vagrant/templates/msehr.vhost.conf.j2
tools/vagrant/templates/msehrCli.sh.j2

permet d'avoir une installation non influencée par la commande `vagrant reload`, tout en pouvant copier via `vagrant provision` et la variable stage = testing,  les modifications du répertoire mappé sur /vagrant

fix: make dir persistent

---

public_html/composer.json

La nouvelle version de composer ne supporte plus les majuscules dans le composer.json et renvoie une erreur

fix: composer not supported uppercases anymore

---

installer/debian-bash-installer.sh

Modification de la génération du certificat en auto-signé SAN pour pouvoir valider l'autorité de certification sur les navigateurs basés sur Chromium

fix: error message on chromium based browser

---

controlers/index.php

fix le bug sur php 8 de l'absence de redirection de localhost vers localhost/patients quand patient today n'est pas configuré
(correction effectuée avec rector après avoir identifié le bon fichier via les logs d'erreurs, testé sur debian sid et ubuntu 22.04 [php8.1])

fix: php80 CountOnNull

---

composer.json

Enlève le message d'erreur de composer pour dompdf. J'ai testé le changement sur des factures et dossiers ça décale légèrement l'entête. Je ne sais pas s'il y a d'autres fonctions à tester pour s'assurer de la compatibilité

fix: dompdf php8

---

class/msModBaseSqlGenerate.php
controlers/rechercher/peopleSearch.php

Sur le nouveau controleur *peopleSearch* de la v7 le cas `$p['page']['prop']`
n'est pas pris en compte ce qui provoque un crash au chargement de la
page `/todays/`.
Ajoute aussi le menu `podt` à `designTopMenuSections` (il ne figure pas par défaut sur la v7 et donc n'est pas affiché dans le menus sauf si on l'ajoute manuellement).

Fix le controleur peopleSearch pour la page /todays/

---

class/msClicRDV.php

Désormais les paramètre utilisateurs doivent être obtenus dupuis
msConcfiguration.

Fix msClicRDV obtention de paramètres utilisateur

---

public_html/composer.json

évite un message d'erreur sur composer 2.2.18 et supérieur

fix: allow-plugin for composer 2.2

---

public_html/install.php

fix l'url de typewatch depuis la mise à jour de composer. Ne règle pas les 302 sur la racine, et le favicon

fix: path typewatch

---

class/msFormValidation.php

Version concerné Medshake EHR/EDC : v7.1.1
Le validateur ne peut valider les options inséré pour un champ select
avec `msFrom::setOptionsForSelect()`.
Dans la méthode `msFrom::_formBuilderBloc()`, les options pour un champ de
type select qui sont inséré dans `$this->_optionsForSelect` sont indexés
par leur `internalName`.
Mais dans la méthode msFormValidation::_formValidationBloc(), la
recherche des "optionsForSelect" qui aurai pu être injecté se fait sur
le nom qui sera utilisé pour nomé l'input dans le html (le "internalName"
préfixé par `p_`.
Fixe se problème en remplaçant `$type['name']` par
`$type['internalName'] pour la recherche des options présente dans
`$this->_optionsForSelect`.

Fix : msFromvalidation indentification des options select insérées

---

controlers/people/actions/inc-action-peopleRegister.php
controlers/people/peopleNew.php
templates/base/dropbox/dropboxViewDoc.html.twig
templates/base/people/peopleNew.html.twig

Version cible Medshake EHR : 7.1.1
Permet de créée un nouveau patient depuis la boite de dépôt en fonction des informations extraites du nom du fichier.
Sur la page de la boite de dépôt un bouton est ajouté sous celui qui
permet de classer un fichier. Au clique sur ce bouton, le formulaire de
création d'un nouveau patient s'ouvre et les informations extraites du nom
du fichier sont pré-remplis. La validation du formulaire classe
automatiquement le fichier de la boite de dépôt dans le dossier du
nouveau patient.

Feat : Nouveau patient depuis un fichier de la dropbox

---

class/msHprim.php
controlers/inbox/actions/inc-ajax-viewMail.php
controlers/inbox/inbox.php
templates/base/inbox/inbox.html.twig
templates/base/inbox/mailView.html.twig

Maintenant qu'APICRYPT peut recevoir des messages de la part de MsSanté,
il est possible d'en recevoir qui ne possède pas d'entête
HPRIM. Ajoute un moyen de vérifier si le message possède bien une entête
HPRIM valide et si ce n'est pas le cas, indique que le message n'en
possède pas plutôt que de tenter d'afficher des informations
incohérentes.
La méthode `msHprim::checkIfValidHprimHeaderData()` peut être grandement
amélioré. J'ai essayé de mettre en place un système de score pour évaluer si
le message possède bien un entête HPRIM valide ou non mais c'est très simpliste
(et je manque d'échantillon de message pour tester sur de nombreux cas de
figure). Pour faire simple le message doit avoir un score de 10 pour considérer
qu'il possède une entête HPRIM valide. Des tests sont passés sur les …

Fix [APICRYPT] : Identifie les messages avec entêtte HPRIM invalide

---

installer/debian-bash-installer.sh

#132 
Lors du lancement du bash d'installation pour Debian, l'utilisateur sera informé de l'invalidité du mot de passe choisi s'il contient des caractères interdits avant de confirmer le mot de passe.

#132 Vérification de l'abscence de caractères interdits dans l'entrée des mots de passe
